//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Urinalysis.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_URINALYSIS_DIALOG           102
#define IDR_URINALYSIS                  103
#define IDR_MAINFRAME                   128
#define IDD_DIALOG_OPTION               135
#define IDB_BITMAP1                     136
#define IDC_CURSOR1                     140
#define IDD_SHOWINF                     141
#define IDD_DIALOG1                     142
#define IDD_REPORTSET                   142
#define IDC_CURSOR2                     143
#define IDC_CURSOR3                     149
#define IDC_CURSOR4                     150
#define IDC_CURSOR5                     154
#define IDD_DIALOG2                     156
#define IDR_MENU1                       158
#define IDR_MENU2                       159
#define IDB_BITMAP2                     160
#define IDC_CURSOR6                     161
#define IDI_ICON1                       162
#define IDD_PREPRINT                    165
#define IDD_DICTIONARY                  166
#define IDD_LOGIN                       170
#define IDB_SPLASH                      174
#define IDB_SPLASH3                     175
#define IDB_LOGO                        180
#define IDC_CURSOR                      192
#define IDI_ICON2                       196
#define IDI_ICON3                       197
#define IDC_CURSOR7                     198
#define IDD_CONNECT                     199
#define IDC_CURSOR8                     200
#define IDI_ICON4                       201
#define IDI_ICON5                       203
#define IDR_MENU3                       206
#define IDD_POSTBACK                    210
#define IDC_OPTION                      1002
#define IDC_BUTTON_THEME                1012
#define IDC_COMBO_THEME                 1013
#define IDC_NAME                        1018
#define IDC_SEX1                        1019
#define IDC_SEX2                        1020
#define IDC_AGE                         1021
#define IDC_CASENUMBER                  1022
#define IDC_SAMPLETYPE                  1024
#define IDC_SAMPLENUMBER                1025
#define IDC_DOCTORNAME                  1026
#define IDC_DEPARTMENT                  1027
#define IDC_TIME                        1030
#define IDC_CONCLUSION                  1031
#define IDC_LIST1                       1032
#define IDC_ITEM1                       1033
#define IDC_ITEM2                       1034
#define IDC_ITEM3                       1035
#define IDC_ITEM4                       1036
#define IDC_ITEM5                       1037
#define IDC_ITEM6                       1038
#define IDC_ITEM7                       1039
#define IDC_ITEM8                       1040
#define IDC_ITEM9                       1041
#define IDC_ITEM10                      1042
#define IDC_ITEM11                      1043
#define IDC_SERACH                      1044
#define IDC_NAMESERACH_EDIT             1047
#define IDC_TIMESERACH_EDIT             1051
#define IDC_NAMESERACH                  1052
#define IDC_TIMESERACH                  1053
#define IDC_SHOWINFORMATION             1057
#define IDC_RADIO1                      1058
#define IDC_RADIO2                      1059
#define IDC_CHECK1                      1061
#define IDC_CHECK2                      1062
#define IDC_CHECK3                      1063
#define IDC_CHECK4                      1064
#define IDC_CHECK5                      1065
#define IDC_CHECK6                      1066
#define IDC_CHECK7                      1067
#define IDC_CHECK8                      1068
#define IDC_CHECK9                      1069
#define IDC_CHECK10                     1070
#define IDC_CHECK11                     1071
#define IDC_SAVEINFORMATION             1073
#define IDC_TIMESHOW                    1074
#define IDC_PRINT                       1075
#define IDC_DATADICTIONARY              1076
#define IDC_LIST2                       1077
#define IDC_EDIT1                       1078
#define IDC_DICTIONARYADD               1079
#define IDC_DICTIONARYDEL               1080
#define IDC_DELETEDATA                  1082
#define IDC_CLEAR                       1083
#define IDC_STATIC1                     1085
#define IDC_REPORTSET                   1087
#define IDC_ADODC1                      1088
#define IDC_DATAGRID1                   1089
#define IDC_REPORTCAPTION               1091
#define IDC_BUTTON1                     1096
#define IDC_LINKBUTTON                  1097
#define IDC_MSCOMM1                     1098
#define IDC_CONNECT                     1099
#define IDC_RADIO3                      1100
#define IDC_RADIO4                      1101
#define IDC_RADIO5                      1102
#define IDC_RADIO6                      1103
#define IDC_RADIO7                      1104
#define IDC_RADIO8                      1105
#define IDC_TIME2                       1106
#define IDC_REFRESHDATA                 1108
#define IDC_POSTBACK                    1109
#define IDC_MONTHCALENDAR1              1112
#define IDC_HELP                        1117

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        219
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1118
#define _APS_NEXT_SYMED_VALUE           104
#endif
#endif
